# Default configuration for Brax continuous control
config = {
    "TOTAL_TIMESTEPS": 50_000_000,
    "NUM_ENVS": 1024,
    "NUM_STEPS": 128,
    "GAMMA": 0.99,
    "CRITIC_TYPE": "fitted",
    "GAE_LAMBDA": 0.95,
    "VALUE_LAMBDA": 0.95,
    "TD_LAMBDA": 0.0,
    "E_LAMBDA": 0.8,
    "RETURN_LAMBDA": 1.0,
    "CLIP_EPS": 0.2,
    "VF_CLIP": 1e6,
    "ENT_COEF": 0.001,
    "ENV_NAME": "hopper",
    "LAYER_NORM": False,
    "NUM_VALUE_HEADS": 1,
    "VALUE_HEAD_AGG": "mean",
    "ACTOR_LR": 3e-4,
    "ACTOR_LR_END": 1e-5,
    "CRITIC_LR": 3e-4,
    "CRITIC_LR_END": 1e-5,
    "ACTOR_EPOCHS": 4,
    "CRITIC_EPOCHS": 4,
    "ACTOR_MINIBATCH_SIZE": 1024,
    "CRITIC_MINIBATCH_SIZE": 1024,
    "NETWORK_CONFIG": {
        "LR": 3e-4,
        "LR_END": 1e-5,
        "NUM_EPOCHS": 4,
        "MINIBATCH_SIZE": 1024,
        "ACTIVATION": "tanh",
        "MAX_GRAD_NORM": 1.0,
        "VF_COEF": 0.5,
        "NORMALIZE_ENV": True,
        "NORMALIZE_REW": True,
        "LR_SCHEDULE": "linear",
    },
}
